### ISSUE TITLE
misleading var name

### ISSUE THREAD

**Issue by tomasmik** [Duovis89/PHP-CLI-APP#14]
https://github.com/Duovis89/PHP-CLI-APP/blob/fc5aad1279a2c10f741143661afd256e14944c0d/get.php#L19

function is called read_input, you return $input from it and then you make it equal to title? huh?

**Comment by Duovis89** [comment]
The user inputs the title of the movie in this case. That is why the read_input is assigned to $title. This seems fine to me.
