### ISSUE TITLE
switch

### ISSUE THREAD

**Issue by tomasmik** [Duovis89/PHP-CLI-APP#19]
https://github.com/Duovis89/PHP-CLI-APP/blob/fc5aad1279a2c10f741143661afd256e14944c0d/get.php#L15

Take a look in to how a switch statement looks - https://www.w3schools.com/php/php_switch.asp

```
case 'title' :{
            /*** returns and array of user specified arguments ***/
            $arguments = checkForAdditionalArguments($argv, $argc);
            $title = read_input(Search_By_Title);
            $data = runCurl($title, Search_By_Title, $arguments);
            SearchPrint($data, $arguments['returnType']);
            break;
        }
        case 'imdb' : {
            $imdb = read_input(Search_By_Imdb);
            $data = runCurl($imdb, Search_By_Imdb, null);
            SearchPrint($data, null);
            break;
        }

```

Also these big cases are hard to read, messy and have repeating code in them. You should be able to refactor this in to functions() of some sort

**Comment by Duovis89** [comment]
cleaned up the dry code with an additional function. Also made switch look a bit cleaner
