### ISSUE TITLE
type jugling

### ISSUE THREAD

**Issue by tomasmik** [Duovis89/PHP-CLI-APP#3]
https://github.com/Duovis89/PHP-CLI-APP/blob/fc5aad1279a2c10f741143661afd256e14944c0d/functions.php#L71

```
    $output = curl_exec($ch);
    if($arguments['returnType'] != 'xml'){
        $output = json_decode($output, true);
    }
    return $output;
```

Why are you doing some weird type juggling here? you are assigning output to curl_exec and then turn it into a result of json_decode

**Comment by Duovis89** [comment]
curl_exec - returns TRUE on success or FALSE on failure. However, if the CURLOPT_RETURNTRANSFER option is set, it will return the result on success, FALSE on failure. This is the reason why I am assigning $output to curl_exec. However I will improve this part of the code as it lacks checking on when curl FAILS.
